# syntax=docker/dockerfile:1
FROM python:3.11-slim-bookworm

# set working directory
RUN mkdir /app

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install backend dependencies
RUN pip install -r requirements.txt

# Copy the rest of the backend code
COPY . .

# Expose the port that the Flask app will run on
EXPOSE 5000

# Start the Flask app
# CMD ["python", "app.py"]
