export const City_Names_Per_RT={
  "01: Cosmopolitan Urban Area": [
    "Delhi NCT",
    "Bangalore",
    "Greater Mumbai",
    "Delhi",
    "NCT Delhi",
    "Chennai",
    "KMA",
    "Hyderabad",
    "Ahmadabad-Gandhinagar",
    "Surat",
    "Lucknow",
    "Jaipur",
    "Pune-PCMC"
  ],
  "02: Sub-Metropolitan Urban Area": [
    "Kanpur",
    "Bhopal",
    "Gurgaon",
    "Vishakhapatnam",
    "Pune-PCMC",
    "Vadodara",
    "Ludhiana",
    "Salem",
    "Bhubaneswar-Cuttack Twin City",
    "Rajkot",
    "Varanasi",
    "Raipur",
    "Jodhpur",
    "Faridabad",
    "Indore",
    "Coimbatore",
    "Ranchi",
    "Thiruvananthapuram",
    "Noida",
    "Kota",
    "Agra",
    "Vijayawada",
    "Nagpur",
    "Thane",
    "Jalandhar",
    "Prayagraj",
    "Tiruchirappalli",
    "Meerut",
    "Ghaziabad",
    "Nashik",
    "Amritsar",
    "Patna",
    "Chandigarh Tricity",
    "Jabalpur",
    "Mysore",
    "Moradabad",
    "Dhanbad",
    "Kalyan-Dombivli",
    "Navi Mumbai",
    "Aurangabad",
    "Solapur",
    "Bareilly",
    "Madurai",
    "Kochi",
    "Guwahati",
    "Aligarh",
    "Gwalior",
    "Saharanpur",
    "KMA",
    "Warangal",
    "Vasai-Virar City",
    "Hubli-Dharwad",
    "Kozhikode"
  ],
  "03: Small Urban Area": [
    "New Delhi",
    "Nashik",
    "Meerut",
    "Aurangabad",
    "Kochi",
    "Solapur",
    "Bhubaneswar-Cuttack Twin City",
    "Chandigarh Tricity",
    "Panvel",
    "Ahmadabad-Gandhinagar",
    "Greater Noida",
    "Hyderabad",
    "Badlapur",
    "Bhiwandi Nizampur",
    "Bahadurgarh",
    "Chennai",
    "Mira-Bhayandar",
    "Mira Bhayandar",
    "Kozhikode",
    "Navi Mumbai Panvel Raigarh",
    "KMA",
    "Loni",
    "Pune-PCMC",
    "Ulhasnagar",
    "Delhi Cantonment Board",
    "Patna",
    "Raipur",
    "Kalher",
    "Kon",
    "Ambarnath",
    "Coimbatore",
    "Delhi Cantonment",
    "Purne",
    "Muradnagar",
    "Kalyan-Dombivli",
    "Thane",
    "Kanpur",
    "Bhiwandi"
  ],
  "04: Semi Urban Area": [
    "Indore",
    "Hyderabad",
    "Coimbatore",
    "Patna",
    "Ahmadabad-Gandhinagar",
    "Guwahati",
    "Agra",
    "Prayagraj",
    "Varanasi",
    "Vijayawada",
    "Ludhiana",
    "Chhapraula",
    "Aurangabad",
    "Ranchi",
    "Kanpur",
    "KMA",
    "Kon",
    "Kochi",
    "Owle",
    "Dhanbad",
    "Bareilly",
    "Gwalior",
    "Tiruchirappalli",
    "Banthla",
    "Pune-PCMC",
    "Thiruvananthapuram",
    "Mysore",
    "Mharal Bk",
    "Haqiqatpur Urf Khudawas",
    "Chennai",
    "Surat",
    "Kundli",
    "Bangalore",
    "Aligarh",
    "Nagpur",
    "Raipur",
    "Madurai",
    "Vadghar",
    "Jaipur",
    "Dasna",
    "Bhondsi",
    "Chandigarh Tricity",
    "Palidevad",
    "Moradabad",
    "Lucknow",
    "Khoni",
    "Nashik",
    "Kambe",
    "Vadodara",
    "Jalandhar",
    "Kozhikode",
    "Jodhpur",
    "Amritsar",
    "Shelar",
    "Jasai",
    "Ladrawan",
    "Abupur",
    "Karivali",
    "Katai",
    "Vishakhapatnam",
    "Salem",
    "Jabalpur",
    "Kharbav",
    "Meerut",
    "Kherli Hafizpur",
    "Rahanal",
    "Rees",
    "Kalher",
    "Purne",
    "Piala",
    "Garhi Harsaru",
    "Bhubaneswar-Cuttack Twin City",
    "Kalundre",
    "Delhi NCR",
    "Bhopal",
    "Badlapur",
    "Manesar",
    "Dadri"
  ]
}