export const City_Names_Per_RT={
  "01: Cosmopolitan Urban Area": [
    "Delhi NCT",
    "Bangalore",
    "Greater Mumbai",
    "Ahmadabad-Gandhinagar",
    "Hyderabad",
    "Chennai",
    "KMA",
    "Pune-PCMC",
    "Surat",
    "Lucknow",
    "Jaipur"
  ],
  "02: Sub-Metropolitan Urban Area": [
    "Nashik",
    "Meerut",
    "Aurangabad",
    "Kochi",
    "Solapur",
    "Bhubaneswar-Cuttack Twin City",
    "Chandigarh Tricity",
    "Kozhikode",
    "Patna",
    "Raipur",
    "Coimbatore",
    "Kalyan-Dombivli",
    "Thane",
    "Kanpur",
    "Indore",
    "Guwahati",
    "Agra",
    "Prayagraj",
    "Varanasi",
    "Vijayawada",
    "Ludhiana",
    "Ranchi",
    "Dhanbad",
    "Bareilly",
    "Gwalior",
    "Tiruchirappalli",
    "Thiruvananthapuram",
    "Mysore",
    "Aligarh",
    "Nagpur",
    "Madurai",
    "Moradabad",
    "Vadodara",
    "Jalandhar",
    "Jodhpur",
    "Amritsar",
    "Vishakhapatnam",
    "Salem",
    "Jabalpur",
    "Bhopal",
    "Gurgaon",
    "Rajkot",
    "Faridabad",
    "Noida",
    "Kota",
    "Ghaziabad",
    "Navi Mumbai",
    "Saharanpur",
    "Warangal",
    "Vasai-Virar City",
    "Hubli-Dharwad"
  ],
  "03: Small Urban Area": [
    "Panvel",
    "Greater Noida",
    "Badlapur",
    "Bhiwandi Nizampur",
    "Bahadurgarh",
    "Mira-Bhayandar",
    "Navi Mumbai Panvel Raigarh",
    "Loni",
    "Ulhasnagar",
    "Kalher",
    "Ambarnath",
    "Purne",
    "Muradnagar",
    "Bhiwandi"
  ],
  "04: Semi Urban Area": [
    "Kon",
    "Chhapraula",
    "Owle",
    "Banthla",
    "Mharal Bk",
    "Haqiqatpur Urf Khudawas",
    "Kundli",
    "Vadghar",
    "Dasna",
    "Bhondsi",
    "Palidevad",
    "Khoni",
    "Kambe",
    "Shelar",
    "Jasai",
    "Ladrawan",
    "Abupur",
    "Karivali",
    "Katai",
    "Kharbav",
    "Kherli Hafizpur",
    "Rahanal",
    "Rees",
    "Piala",
    "Garhi Harsaru",
    "Kalundre",
    "Manesar",
    "Dadri"
  ]
}